require 'json'

module TaxYouProjectMap
  module_function

  def markdown_link(path, label = path)
    "[#{label}](../#{path})"
  end

  def files(root, pattern)
    Dir[File.join(root, pattern)].select { |path| File.file?(path) }
      .map { |path| path.delete_prefix("#{root}/") }.sort
  end

  def render(root, registry = nil)
    registry ||= JSON.parse(File.read(File.join(root, 'calculator-registry.json')))
    categories = registry.fetch('categories')
    rankings = registry.fetch('rankingCategories', [])
    calculator_count = categories.sum { |category| category.fetch('calculators').length }
    ranking_count = rankings.sum { |category| category.fetch('pages').length }
    ignored_directories = %w[.git .agents .codex]
    directories = Dir.children(root).select do |name|
      !ignored_directories.include?(name) && File.directory?(File.join(root, name))
    end.sort

    shell_files = %w[style.css scripts/common.js scripts/calculator-page.js scripts/export-report.js]
    math_files = files(root, 'scripts/*-math.js')
    controller_files = files(root, 'scripts/*-calculators.js')
    table_files = files(root, 'scripts/*-table.js')
    all_scripts = files(root, 'scripts/*.js')
    page_scripts = all_scripts - shell_files - math_files - controller_files - table_files

    category_rows = categories.map do |category|
      pages = category.fetch('calculators').map do |calculator|
        markdown_link(calculator.fetch('file'), calculator.fetch('name'))
      end.join('<br>')
      "| #{category.fetch('group')} | `#{category.fetch('id')}` | #{category.fetch('label')} | #{category.fetch('calculators').length} | #{pages} |"
    end.join("\n")

    hub_rows = registry.fetch('hubs', []).map do |hub|
      "| Hub | #{markdown_link(hub.fetch('file'), hub.fetch('name'))} |"
    end
    ranking_rows = rankings.flat_map do |category|
      category.fetch('pages').map do |page|
        "| #{category.fetch('label')} | #{markdown_link(page.fetch('file'), page.fetch('name'))} |"
      end
    end

    inventory = [
      ['페이지 메타데이터', markdown_link('src/page-metadata.json')],
      ['페이지별 본문', "#{markdown_link('src/pages/', 'src/pages/*.html.erb')} (#{files(root, 'src/pages/*.html.erb').length}개)"],
      ['공통 페이지 셸', markdown_link('src/partials/', 'src/partials/')],
      ['검색 노출·발행 정보', markdown_link('src/site-discovery.json')],
      ['공통 화면·내보내기', shell_files.map { |path| markdown_link(path) }.join('<br>')],
      ['순수 계산 엔진', "#{markdown_link('scripts/', 'scripts/*-math.js')} (#{math_files.length}개)"],
      ['공유 UI 컨트롤러', "#{markdown_link('scripts/', 'scripts/*-calculators.js')} (#{controller_files.length}개)"],
      ['공식 데이터 테이블', "#{markdown_link('scripts/', 'scripts/*-table.js')} (#{table_files.length}개)"],
      ['페이지별 스크립트', "#{markdown_link('scripts/', 'scripts/*.js')} (#{page_scripts.length}개)"],
      ['테스트', markdown_link('tests/', 'tests/')],
      ['개발 도구', markdown_link('tools/', 'tools/')]
    ].map { |role, location| "| #{role} | #{location} |" }.join("\n")

    docs = files(root, 'docs/*.md').reject { |path| path == 'docs/project-map.md' }

    <<~MARKDOWN
      <!-- AUTO-GENERATED by `ruby tools/taxyou-context.rb --write-map`. DO NOT EDIT. -->
      # TaxYou project map

      `calculator-registry.json`과 현재 파일 구조에서 생성한 탐색용 문서입니다. 직접 수정하지 말고 `npm run docs:sync`로 갱신하세요.

      ## 현재 상태

      - 레지스트리 검토일: #{registry.fetch('reviewedAt')}
      - 계산기: #{calculator_count}개 / 카테고리: #{categories.length}개
      - 순위·비교 페이지: #{ranking_count}개
      - 최상위 작업 디렉터리: #{directories.map { |name| "`#{name}/`" }.join(', ')}
      - 운영 URL: #{registry.fetch('siteOrigin')}

      ## 페이지와 카테고리

      | 그룹 | 카테고리 ID | 화면 이름 | 수 | 페이지 |
      |---|---|---|---:|---|
      #{category_rows}

      ## 허브와 순위 페이지

      | 유형 | 페이지 |
      |---|---|
      #{(hub_rows + ranking_rows).join("\n")}

      ## 코드 위치

      | 역할 | 파일 |
      |---|---|
      #{inventory}

      ## 문서 선택

      - 저장소 작업 규칙: #{markdown_link('AGENTS.md')}
      - 구조와 책임 경계: #{markdown_link('docs/taxyou-architecture.md')}
      - 계산기 구현 절차: #{markdown_link('docs/calculator-implementation-guide.md')}
      - 완료 전 검사: #{markdown_link('docs/calculator-completion-checklist.md')}
      - 도메인별 근거: #{docs.reject { |path| %w[docs/taxyou-architecture.md docs/calculator-implementation-guide.md docs/calculator-completion-checklist.md].include?(path) }.map { |path| markdown_link(path) }.join(', ')}

      개발 흐름과 검증 명령은 #{markdown_link('AGENTS.md')}를 기준으로 합니다.
    MARKDOWN
  end
end
