require 'json'

module TaxYouProjectMap
  module_function

  def markdown_link(path, label = path)
    "[#{label}](../#{path})"
  end

  def file_links(paths)
    paths.map { |path| markdown_link(path) }.join('<br>')
  end

  def files(root, pattern)
    Dir[File.join(root, pattern)].select { |path| File.file?(path) }
      .map { |path| path.delete_prefix("#{root}/") }.sort
  end

  def render(root, registry = nil)
    registry ||= JSON.parse(File.read(File.join(root, 'calculator-registry.json')))
    categories = registry.fetch('categories')
    rankings = registry.fetch('rankingCategories', [])
    calculator_count = categories.sum { |category| category.fetch('calculators').length }
    ranking_count = rankings.sum { |category| category.fetch('pages').length }
    ignored_directories = %w[.git .agents .codex]
    directories = Dir.children(root).select do |name|
      !ignored_directories.include?(name) && File.directory?(File.join(root, name))
    end.sort

    shell_files = %w[style.css scripts/common.js scripts/calculator-page.js scripts/export-report.js]
    math_files = files(root, 'scripts/*-math.js')
    controller_files = files(root, 'scripts/*-calculators.js')
    table_files = files(root, 'scripts/*-table.js')
    all_scripts = files(root, 'scripts/*.js')
    page_scripts = all_scripts - shell_files - math_files - controller_files - table_files

    category_rows = categories.map do |category|
      pages = category.fetch('calculators').map do |calculator|
        markdown_link(calculator.fetch('file'), calculator.fetch('name'))
      end.join('<br>')
      "| #{category.fetch('group')} | `#{category.fetch('id')}` | #{category.fetch('label')} | #{category.fetch('calculators').length} | #{pages} |"
    end.join("\n")

    hub_rows = registry.fetch('hubs', []).map do |hub|
      "| Hub | #{markdown_link(hub.fetch('file'), hub.fetch('name'))} |"
    end
    ranking_rows = rankings.flat_map do |category|
      category.fetch('pages').map do |page|
        "| #{category.fetch('label')} | #{markdown_link(page.fetch('file'), page.fetch('name'))} |"
      end
    end

    inventory = [
      ['공통 화면·내보내기', shell_files],
      ['순수 계산 엔진', math_files],
      ['공유 UI 컨트롤러', controller_files],
      ['공식 데이터 테이블', table_files],
      ['페이지별 계산 스크립트', page_scripts],
      ['API', files(root, 'api/**/*')],
      ['템플릿', files(root, 'templates/**/*')],
      ['테스트', files(root, 'tests/**/*')],
      ['개발 도구', files(root, 'tools/**/*')]
    ].reject { |_, paths| paths.empty? }.map do |role, paths|
      "| #{role} | #{file_links(paths)} |"
    end.join("\n")

    docs = files(root, 'docs/*.md').reject { |path| path == 'docs/project-map.md' }

    <<~MARKDOWN
      <!-- AUTO-GENERATED by `ruby tools/taxyou-context.rb --write-map`. DO NOT EDIT. -->
      # TaxYou project map

      `calculator-registry.json`과 현재 파일 구조에서 생성한 탐색용 문서입니다. 직접 수정하지 말고 `npm run docs:sync`로 갱신하세요.

      ## 현재 상태

      - 레지스트리 검토일: #{registry.fetch('reviewedAt')}
      - 계산기: #{calculator_count}개 / 카테고리: #{categories.length}개
      - 순위·비교 페이지: #{ranking_count}개
      - 최상위 작업 디렉터리: #{directories.map { |name| "`#{name}/`" }.join(', ')}
      - 운영 URL: #{registry.fetch('siteOrigin')}

      ## 페이지와 카테고리

      | 그룹 | 카테고리 ID | 화면 이름 | 수 | 페이지 |
      |---|---|---|---:|---|
      #{category_rows}

      ## 허브와 순위 페이지

      | 유형 | 페이지 |
      |---|---|
      #{(hub_rows + ranking_rows).join("\n")}

      ## 코드 위치

      | 역할 | 파일 |
      |---|---|
      #{inventory}

      ## 변경 동기화 경로

      새 계산기나 카테고리는 `calculator-registry.json`을 기준으로 `index.html`의 카드·ItemList, 해당 페이지의 breadcrumb·canonical, `about.html`, `sitemap.xml`, 신규 공개 시 `rss.xml`을 같은 URL과 이름으로 연결합니다. 구조 또는 레지스트리를 바꾼 뒤 `npm run docs:sync`를 실행합니다. 프로젝트 맵이 현재 상태와 다르면 컨텍스트 검사와 정적 사이트 검사가 실패합니다.

      ## 문서 선택

      - 저장소 작업 규칙: #{markdown_link('AGENTS.md')}
      - 구조와 책임 경계: #{markdown_link('docs/taxyou-architecture.md')}
      - 계산기 구현 절차: #{markdown_link('docs/calculator-implementation-guide.md')}
      - 완료 전 검사: #{markdown_link('docs/calculator-completion-checklist.md')}
      - 도메인별 근거: #{docs.reject { |path| %w[docs/taxyou-architecture.md docs/calculator-implementation-guide.md docs/calculator-completion-checklist.md].include?(path) }.map { |path| markdown_link(path) }.join(', ')}

      ## 빠른 명령

      ```sh
      ruby tools/taxyou-context.rb --check
      ruby tools/taxyou-context.rb --category CATEGORY_ID --pretty
      npm run docs:sync
      npm test
      xmllint --noout sitemap.xml rss.xml
      git diff --check
      ```
    MARKDOWN
  end
end
